name: Consumer1

on:
  workflow_dispatch:

jobs:    
  list-files:
    runs-on: ubuntu-latest
    needs: call-producer
    steps:
      - uses: ./.github/workflows/producer.yml
      - name: list files
        run: ls . -R
