name: Consumer1

on:
  workflow_dispatch:

jobs:    
  list-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.1
      - uses: ./.github/workflows/producer.yml
      - name: list files
        run: ls . -R
