name: Consumer1

on:
  workflow_dispatch:

jobs:
  call-producer:
    uses: ./.github/workflows/producer.yml
    
  list-files:
    runs-on: ubuntu-latest
    needs: call-producer
    steps:
      - name: list files
        run: ls . -R
