name: Consumer1

on:
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/producer.yml
    
  build:
    runs-on: ubuntu-latest
    needs: call
    steps:
      - name: list files
        run: ls . -R
