name: mac ssh

on:
  workflow_dispatch:

jobs:    
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Setup java 17
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          distribution: temurin
          java-version: 17
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
